### ISSUE TITLE
NoSuchMethodError: LvsPlayerError working with compose version 2024.06.00 

### ISSUE THREAD

**Issue by Ouflores** [bambuser/BambuserPlayerSDK-Android#21]
1. Update compose version 2023.03.00 ->  2024.06.00
2. When try to start video player.

<img width="1378" alt="Captura de pantalla 2024-08-12 a la(s) 6 31 43 a m" src="https://github.com/user-attachments/assets/0c95c322-7363-44b6-b246-d508496053b6">

**Comment by SimovicIvan** [comment]
Should be fixed in a few days.

**Comment by SimovicIvan** [comment]
Fixed in release [1.3.0](https://github.com/bambuser/BambuserPlayerSDK-Android/releases/tag/1.3.0)
