### ISSUE TITLE
LVSPlayerActivity: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Ouflores** [bambuser/BambuserPlayerSDK-Android#36]
Hello team when are getting next crash when we try to display the live video.
We where using 1.3.0 version (in this version we detect the crash), we try to upgrade our library to 2.0.0 but the issue persists

```
Fatal Exception: java.lang.NoSuchMethodError: No static method rememberSnapFlingBehavior(Landroidx/compose/foundation/lazy/LazyListState;Landroidx/compose/runtime/Composer;I)Landroidx/compose/foundation/gestures/FlingBehavior; in class Landroidx/compose/foundation/gestures/snapping/LazyListSnapLayoutInfoProviderKt; or its super classes (declaration of 'androidx.compose.foundation.gestures.snapping.LazyListSnapLayoutInfoProviderKt' appears in /data/app/~~Q6BijpIsl5HOUhRHlk69hg==/mx.com.liverpool.shoppingapp.qa-dmXaDn7-IBjn5rzJ31ding==/base.apk)
       at com.bambuser.player.mu.b(SourceFile:3738)
       at com.bambuser.player.mu.a(SourceFile:3559)
       at com.bambuser.player.wu.a(SourceFile:129)
       at com.bambuser.player.el.a(SourceFile:7115)
       at com.bambuser.player.el.a(SourceFile:3551)
       at com.bambuser.player.el.a(SourceFile:2578)
       at com.bambuser.player.pk.invoke(SourceFile:430)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
       at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:130)
       at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:129)
       at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
       at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
       at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
       at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
       at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
       at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
       at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
       at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
```

**Comment by zeyadsadaqa** [comment]
Hello @Ouflores Is this issue happening only when you upgraded to v `2.0.0`? or was it there with `1.3.0 `?
What crash did you encounter with `1.3.0`?

**Comment by Ouflores** [comment]
@zeyadsadaqa In both versions.
We detect the crash in v1.3.0....then we try to update to 2.0.0 but the crash was not resolved.

**Comment by zeyadsadaqa** [comment]
@Ouflores What version of compose do you use in your project?

**Comment by arturschwarz** [comment]
We are experiencing the same issue. We have tried fixing it by updating our compose bom to a newer version (2024.08.00 to 2024.10.01) which resulted in basically the same crash but connected to a different method:

```
java.lang.NoSuchMethodError: No static method rememberModalBottomSheetState(ZLkotlin/jvm/functions/Function1;Landroidx/compose/runtime/Composer;II)Landroidx/compose/material3/SheetState; in class Landroidx/compose/material3/ModalBottomSheet_androidKt; or its super classes (declaration of 'androidx.compose.material3.ModalBottomSheet_androidKt' appears in /data/app/~~zCrKVycYYBaMOiApyoe8HA==/de.dm.meindm.android.local-ziykvK4sUcm0kMAUHfM8fQ==/base.apk)
     at com.bambuser.player.o4.a(SourceFile:3978)
     at com.bambuser.player.el.a(SourceFile:6893)
     at com.bambuser.player.el.a(SourceFile:3551)
     at com.bambuser.player.el.a(SourceFile:2578)
     at com.bambuser.player.pk.invoke(SourceFile:430)
     ...
``` 

Our versions:
bambuser: 1.3.2
compose bom: 2024.08.00
compileSdk: 34
targetSdk: 34
minSdk: 26

(The crash also happens when updating bambuser SDK to 2.0.0)

**Comment by zeyadsadaqa** [comment]
We are using `2024.06.00` you can use the same version to avoid conflicts and method mismatch.
If you require using `2024.10.01`, please ask your contact person to direct this request to our contact person, so it can go to our backlog

**Comment by arturschwarz** [comment]
@zeyadsadaqa Downgrading compose in a multi-module project is no option. This needs to be fixed within the SDK.

**Comment by zeyadsadaqa** [comment]
@arturschwarz @Ouflores We are going to fix it in our next release, upgrading  the compose BOM to 24.11.00

**Comment by zeyadsadaqa** [comment]
This should be fixed in the SDK version 2.1.1
FYI: @arturschwarz , @Ouflores
